import { registerRoute } from "workbox-routing";
import { precacheAndRoute } from 'workbox-precaching';
import { ExpirationPlugin } from "workbox-expiration";
import {
    CacheFirst,
    StaleWhileRevalidate,
    NetworkFirst
  } from "workbox-strategies";
// manifest import will be autogenerated by webpack
precacheAndRoute(self.__WB_MANIFEST || []);

registerRoute(
    /\.(?:js|css|scss)$/,
    new NetworkFirst({
      cacheName: "static-resources",
      plugins: [
        new ExpirationPlugin({
          maxEntries: 60,
          maxAgeSeconds: 20 * 24 * 60 * 60 // 20 Days
        })
      ]
    })
);
  